/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
*/
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => PasswordGeneratorPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = {
  defaultSalt: "obsidian-salt",
  defaultLength: 16,
  defaultIterations: 1e5
};
var LOCK_ICON = `
<svg width="100" height="100" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
<path d="M12 2C9.243 2 7 4.243 7 7V9H6C4.895 9 4 9.895 4 11V20C4 21.105 4.895 22 6 22H18C19.105 22 20 21.105 20 20V11C20 9.895 19.105 9 18 9H17V7C17 4.243 14.757 2 12 2ZM12 4C13.654 4 15 5.346 15 7V9H9V7C9 5.346 10.346 4 12 4ZM18 11V20H6V11H18Z" fill="currentColor"/>
</svg>`;
var PasswordGeneratorView = class extends import_obsidian.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.plugin = plugin;
  }
  getViewType() {
    return "password-generator-sidebar";
  }
  getDisplayText() {
    return "\u0413\u0435\u043D\u0435\u0440\u0430\u0442\u043E\u0440 \u043F\u0430\u0440\u043E\u043B\u0435\u0439";
  }
  getIcon() {
    return "lock";
  }
  async onOpen() {
    const container = this.containerEl.children[1];
    container.empty();
    container.addClass("password-generator-sidebar");
    const header = container.createDiv("sidebar-header");
    header.createEl("h2", { text: "\u0413\u0435\u043D\u0435\u0440\u0430\u0442\u043E\u0440 \u043F\u0430\u0440\u043E\u043B\u0435\u0439" });
    const formContainer = container.createDiv("password-form-container");
    const wordSetting = new import_obsidian.Setting(formContainer).setName("\u0411\u0430\u0437\u043E\u0432\u043E\u0435 \u0441\u043B\u043E\u0432\u043E").setDesc("\u0421\u043B\u043E\u0432\u043E \u0438\u043B\u0438 \u0444\u0440\u0430\u0437\u0430 \u0434\u043B\u044F \u0433\u0435\u043D\u0435\u0440\u0430\u0446\u0438\u0438").addText((text) => {
      this.wordInput = text.inputEl;
      text.setPlaceholder("\u0412\u0432\u0435\u0434\u0438\u0442\u0435 \u0441\u043B\u043E\u0432\u043E").setValue(this.plugin.currentWord || "").onChange((value) => this.plugin.currentWord = value);
    });
    const saltSetting = new import_obsidian.Setting(formContainer).setName("\u0421\u043E\u043B\u044C").setDesc("\u0414\u043E\u043F\u043E\u043B\u043D\u0438\u0442\u0435\u043B\u044C\u043D\u0430\u044F \u0441\u043E\u043B\u044C \u0434\u043B\u044F \u0445\u0435\u0448\u0438\u0440\u043E\u0432\u0430\u043D\u0438\u044F").addText((text) => {
      this.saltInput = text.inputEl;
      text.setPlaceholder("\u0412\u0432\u0435\u0434\u0438\u0442\u0435 \u0441\u043E\u043B\u044C").setValue(this.plugin.currentSalt || this.plugin.settings.defaultSalt).onChange((value) => this.plugin.currentSalt = value);
    });
    const lengthSetting = new import_obsidian.Setting(formContainer).setName("\u0414\u043B\u0438\u043D\u0430 \u043F\u0430\u0440\u043E\u043B\u044F").setDesc("\u041A\u043E\u043B\u0438\u0447\u0435\u0441\u0442\u0432\u043E \u0441\u0438\u043C\u0432\u043E\u043B\u043E\u0432 (8-32)").addSlider((slider) => {
      this.lengthSlider = slider.sliderEl;
      slider.setLimits(8, 32, 1).setValue(this.plugin.currentLength).onChange((value) => this.plugin.currentLength = value).setDynamicTooltip();
    });
    const iterationsSetting = new import_obsidian.Setting(formContainer).setName("\u0418\u0442\u0435\u0440\u0430\u0446\u0438\u0438").setDesc("\u041A\u043E\u043B\u0438\u0447\u0435\u0441\u0442\u0432\u043E \u0440\u0430\u0443\u043D\u0434\u043E\u0432 \u0445\u0435\u0448\u0438\u0440\u043E\u0432\u0430\u043D\u0438\u044F").addSlider((slider) => {
      this.iterationsSlider = slider.sliderEl;
      slider.setLimits(1e4, 5e5, 1e4).setValue(this.plugin.currentIterations).onChange((value) => this.plugin.currentIterations = value).setDynamicTooltip();
    });
    const outputContainer = container.createDiv("password-output-container");
    outputContainer.createEl("h3", { text: "\u0421\u0433\u0435\u043D\u0435\u0440\u0438\u0440\u043E\u0432\u0430\u043D\u043D\u044B\u0439 \u043F\u0430\u0440\u043E\u043B\u044C" });
    this.passwordOutput = outputContainer.createDiv("password-output");
    this.passwordOutput.setText("\u041F\u0430\u0440\u043E\u043B\u044C \u043F\u043E\u044F\u0432\u0438\u0442\u0441\u044F \u0437\u0434\u0435\u0441\u044C");
    const buttonContainer = container.createDiv("button-container");
    new import_obsidian.Setting(buttonContainer).addButton((btn) => btn.setButtonText("\u0421\u0433\u0435\u043D\u0435\u0440\u0438\u0440\u043E\u0432\u0430\u0442\u044C \u043F\u0430\u0440\u043E\u043B\u044C").setCta().onClick(async () => {
      if (!this.plugin.currentWord || this.plugin.currentWord.trim() === "") {
        new import_obsidian.Notice("\u0412\u0432\u0435\u0434\u0438\u0442\u0435 \u0431\u0430\u0437\u043E\u0432\u043E\u0435 \u0441\u043B\u043E\u0432\u043E");
        return;
      }
      if (!this.plugin.currentSalt || this.plugin.currentSalt.trim() === "") {
        new import_obsidian.Notice("\u0412\u0432\u0435\u0434\u0438\u0442\u0435 \u0441\u043E\u043B\u044C");
        return;
      }
      await this.generateAndShowPassword();
    }));
  }
  async onClose() {
  }
  async generateAndShowPassword() {
    try {
      this.passwordOutput.setText("\u0413\u0435\u043D\u0435\u0440\u0430\u0446\u0438\u044F...");
      this.passwordOutput.addClass("generating");
      const password = await this.plugin.generatePasswordHash(
        this.plugin.currentWord,
        this.plugin.currentSalt,
        this.plugin.currentLength,
        this.plugin.currentIterations
      );
      this.passwordOutput.setText(password);
      this.passwordOutput.removeClass("generating");
      this.passwordOutput.addClass("generated");
      await this.copyPasswordToClipboard(password);
    } catch (error) {
      console.error("\u041E\u0448\u0438\u0431\u043A\u0430 \u0433\u0435\u043D\u0435\u0440\u0430\u0446\u0438\u0438:", error);
      this.passwordOutput.setText("\u041E\u0448\u0438\u0431\u043A\u0430 \u0433\u0435\u043D\u0435\u0440\u0430\u0446\u0438\u0438");
      this.passwordOutput.removeClass("generating");
      this.passwordOutput.addClass("error");
      new import_obsidian.Notice("\u041E\u0448\u0438\u0431\u043A\u0430 \u0433\u0435\u043D\u0435\u0440\u0430\u0446\u0438\u0438 \u043F\u0430\u0440\u043E\u043B\u044F. \u041F\u0440\u043E\u0432\u0435\u0440\u044C\u0442\u0435 \u043A\u043E\u043D\u0441\u043E\u043B\u044C.");
    }
  }
  async copyPasswordToClipboard(password) {
    try {
      await navigator.clipboard.writeText(password);
      new import_obsidian.Notice("\u041F\u0430\u0440\u043E\u043B\u044C \u0441\u043A\u043E\u043F\u0438\u0440\u043E\u0432\u0430\u043D \u0432 \u0431\u0443\u0444\u0435\u0440 \u043E\u0431\u043C\u0435\u043D\u0430");
    } catch (error) {
      console.error("\u041E\u0448\u0438\u0431\u043A\u0430 \u043A\u043E\u043F\u0438\u0440\u043E\u0432\u0430\u043D\u0438\u044F:", error);
      new import_obsidian.Notice("\u041D\u0435 \u0443\u0434\u0430\u043B\u043E\u0441\u044C \u0441\u043A\u043E\u043F\u0438\u0440\u043E\u0432\u0430\u0442\u044C \u043F\u0430\u0440\u043E\u043B\u044C");
    }
  }
};
var PasswordGeneratorPlugin = class extends import_obsidian.Plugin {
  constructor() {
    super(...arguments);
    this.currentWord = "";
    this.currentSalt = "";
    this.currentLength = 16;
    this.currentIterations = 1e5;
  }
  async onload() {
    await this.loadSettings();
    (0, import_obsidian.addIcon)("lock", LOCK_ICON);
    this.addRibbonIcon("lock", "\u0413\u0435\u043D\u0435\u0440\u0430\u0442\u043E\u0440 \u043F\u0430\u0440\u043E\u043B\u0435\u0439", (evt) => {
      this.activateView();
    });
    this.registerView(
      "password-generator-sidebar",
      (leaf) => new PasswordGeneratorView(leaf, this)
    );
    this.addSettingTab(new PasswordSettingTab(this.app, this));
  }
  // Активация боковой панели
  async activateView() {
    const { workspace } = this.app;
    const existingLeaf = workspace.getLeavesOfType("password-generator-sidebar");
    if (existingLeaf.length > 0) {
      workspace.revealLeaf(existingLeaf[0]);
      return;
    }
    const leaf = workspace.getRightLeaf(false);
    if (leaf) {
      await leaf.setViewState({
        type: "password-generator-sidebar",
        active: true
      });
      workspace.revealLeaf(leaf);
    }
  }
  async generatePasswordHash(word, salt, length, iterations) {
    try {
      const encoder = new TextEncoder();
      const keyMaterial = await crypto.subtle.importKey(
        "raw",
        encoder.encode(word),
        { name: "PBKDF2" },
        false,
        ["deriveBits"]
      );
      const derivedBits = await crypto.subtle.deriveBits(
        {
          name: "PBKDF2",
          salt: encoder.encode(salt),
          iterations,
          hash: "SHA-256"
        },
        keyMaterial,
        256
        // бит
      );
      const hashArray = Array.from(new Uint8Array(derivedBits));
      const hashHex = hashArray.map((b) => b.toString(16).padStart(2, "0")).join("");
      return this.formatHashAsPassword(hashHex, length);
    } catch (error) {
      console.error("\u041E\u0448\u0438\u0431\u043A\u0430 \u0432 generatePasswordHash:", error);
      throw new Error(`\u041D\u0435 \u0443\u0434\u0430\u043B\u043E\u0441\u044C \u0441\u0433\u0435\u043D\u0435\u0440\u0438\u0440\u043E\u0432\u0430\u0442\u044C \u0445\u0435\u0448: ${error.message}`);
    }
  }
  formatHashAsPassword(hashHex, length) {
    const allChars = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789!@#$%^&*()_+-=[]{}|;:,.<>?";
    let password = "";
    for (let i = 0; i < length; i++) {
      const hashByte = parseInt(hashHex.substr(i * 2 % hashHex.length, 2), 16);
      password += allChars[hashByte % allChars.length];
    }
    return this.ensurePasswordRequirements(password, hashHex);
  }
  ensurePasswordRequirements(password, hashHex) {
    const hasUpperCase = /[A-Z]/.test(password);
    const hasLowerCase = /[a-z]/.test(password);
    const hasNumbers = /\d/.test(password);
    const hasSpecial = /[!@#$%^&*()_+\-=\[\]{}|;:,.<>?]/.test(password);
    if (hasUpperCase && hasLowerCase && hasNumbers && hasSpecial) {
      return password;
    }
    const chars = password.split("");
    const checks = [hasUpperCase, hasLowerCase, hasNumbers, hasSpecial];
    const replacements = [
      "ABCDEFGHIJKLMNOPQRSTUVWXYZ",
      "abcdefghijklmnopqrstuvwxyz",
      "0123456789",
      "!@#$%^&*()_+-=[]{}|;:,.<>?"
    ];
    for (let i = 0; i < checks.length; i++) {
      if (!checks[i]) {
        const hashPart = hashHex.substr(i * 8, 8);
        const position = parseInt(hashPart.substr(0, 4), 16) % chars.length;
        const charIndex = parseInt(hashPart.substr(4, 4), 16) % replacements[i].length;
        chars[position] = replacements[i][charIndex];
      }
    }
    return chars.join("");
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
    this.currentSalt = this.settings.defaultSalt;
    this.currentLength = this.settings.defaultLength;
    this.currentIterations = this.settings.defaultIterations;
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
};
var PasswordSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "\u041D\u0430\u0441\u0442\u0440\u043E\u0439\u043A\u0438 \u0433\u0435\u043D\u0435\u0440\u0430\u0442\u043E\u0440\u0430 \u043F\u0430\u0440\u043E\u043B\u0435\u0439" });
    new import_obsidian.Setting(containerEl).setName("\u0421\u043E\u043B\u044C \u043F\u043E \u0443\u043C\u043E\u043B\u0447\u0430\u043D\u0438\u044E").setDesc("\u0418\u0441\u043F\u043E\u043B\u044C\u0437\u0443\u0435\u0442\u0441\u044F \u043F\u0440\u0438 \u043A\u0430\u0436\u0434\u043E\u043C \u0437\u0430\u043F\u0443\u0441\u043A\u0435").addText((text) => text.setValue(this.plugin.settings.defaultSalt).onChange(async (value) => {
      this.plugin.settings.defaultSalt = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("\u0414\u043B\u0438\u043D\u0430 \u043F\u0430\u0440\u043E\u043B\u044F \u043F\u043E \u0443\u043C\u043E\u043B\u0447\u0430\u043D\u0438\u044E").setDesc("\u041A\u043E\u043B\u0438\u0447\u0435\u0441\u0442\u0432\u043E \u0441\u0438\u043C\u0432\u043E\u043B\u043E\u0432").addSlider((slider) => slider.setLimits(8, 32, 1).setValue(this.plugin.settings.defaultLength).onChange(async (value) => {
      this.plugin.settings.defaultLength = value;
      await this.plugin.saveSettings();
    }).setDynamicTooltip());
    new import_obsidian.Setting(containerEl).setName("\u0418\u0442\u0435\u0440\u0430\u0446\u0438\u0438 \u043F\u043E \u0443\u043C\u043E\u043B\u0447\u0430\u043D\u0438\u044E").setDesc("\u041A\u043E\u043B\u0438\u0447\u0435\u0441\u0442\u0432\u043E \u0440\u0430\u0443\u043D\u0434\u043E\u0432 \u0445\u0435\u0448\u0438\u0440\u043E\u0432\u0430\u043D\u0438\u044F").addSlider((slider) => slider.setLimits(1e4, 5e5, 1e4).setValue(this.plugin.settings.defaultIterations).onChange(async (value) => {
      this.plugin.settings.defaultIterations = value;
      await this.plugin.saveSettings();
    }).setDynamicTooltip());
  }
};
